{% set name = "spindry" %}
{% set version = "0.0.91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SpinDry-{{ version }}.tar.gz
  sha256: 4a4d9b899e1faed3b08b1c0e2f8fc4b214cd14657cdf7988b87eac420d534678

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - matplotlib-base
    - networkx
    - numpy

test:
  imports:
    - spindry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andrewtarzia/SpinDry
  summary: Contains MC algorithm for generating host-guest conformers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
