{% set name = "spindry" %}
{% set version = "2024.2.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/SpinDry-{{ version }}.tar.gz
  sha256: cbd67c9bd84c633b0994c42dd45eca2caf4e601476b99f87dda52eec5605e7e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - mchammer
    - python >={{ python_min }}
    - scipy
    - matplotlib-base
    - networkx
    - numpy

test:
  imports:
    - spindry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/andrewtarzia/SpinDry
  summary: Contains MC algorithm for generating host-guest conformers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
