{% set name = "spindry" %}
{% set version = "2026.3.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 446244902eae73934d4b81d8a026860606520012b92a6fefbd7713598acae7e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - mchammer
    - python >={{ python_min }}
    - scipy
    - matplotlib-base
    - networkx
    - numpy

test:
  imports:
    - spindry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/andrewtarzia/SpinDry
  summary: Contains MC algorithm for generating host-guest conformers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
